# Generated by Django 3.2.7 on 2021-10-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('tags', models.CharField(default='', max_length=130)),
                ('price', models.FloatField(default=0.0)),
                ('public_id', models.CharField(default='e4e1c584-1ac6-4e9d-bd58-38e5f0ae2161', max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('discount', models.BooleanField(default=False)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('rating', models.CharField(default='[4]', max_length=1300)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('verified', models.BooleanField(default=False)),
                ('public_id', models.CharField(default='02f676e1-5f33-433a-9a23-5b12079432f0', max_length=300)),
                ('rating', models.CharField(default='[4]', max_length=1300)),
                ('user_id', models.IntegerField(default=1000000)),
                ('enrolled_courses', models.TextField(default='{}')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(default=0)),
                ('links', models.CharField(default='[]', max_length=33)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor'),
        ),
    ]
