# Generated by Django 3.2.7 on 2021-10-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=33)),
                ('lastname', models.CharField(max_length=33)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=33)),
                ('headline', models.TextField(default='headline')),
                ('public_id', models.CharField(default='2f149e92-f2cc-4273-8342-dc84a11a721c', max_length=300)),
                ('user_id', models.IntegerField(default=10000000)),
                ('active', models.BooleanField(default=True)),
                ('cart', models.TextField(default='[]')),
                ('wishlist', models.TextField(default='[]')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='tutor.Course')),
                ('fav_courses', models.ManyToManyField(blank=True, related_name='students_fav', to='tutor.Course')),
            ],
        ),
    ]
